### ISSUE TITLE
Script request: how to proxy an http video livestream and make it http(s) instead 

### ISSUE THREAD

**Issue by inglesuniversal** [php-curl-class/php-curl-class#715] opened 2022-05-24 21:39 UTC
I have HLS player which users Video.js player script

my problem is playing streams which come from HTTP address which are blocked if my site is hosted with an SSL so it is blocked and a MIXED content error is displayed in the browser's console.

How can I proxy this source video using your script and enable HTTPS?

sample source url:

[HTTP_LIVESTREAM](http://51.161.118.146:8080/ISG03_ABC_CHICAGO_IL_WLS/video.m3u8)

**Comment by zachborboa** [comment] 2022-06-23 13:58
Hi. This appears to be a dupe of #637.

**Closed by zachborboa** 2022-06-23 13:58 UTC
