### ISSUE TITLE
Feature request: Create a proxy connection with Curl for URLs with livestream.m3u8

### ISSUE THREAD

**Issue by inglesuniversal** [php-curl-class/php-curl-class#654] opened 2020-11-21 18:50 UTC
Input URL:  http://domain/live/stream.m3u8

::::CURL::::::

output URL:   https://mydomain.com/?url=http://domain/live/stream.m3u8

Thanks, buy chrome won't allow me to stream non https urls if my site has SSL connection

**Comment by zachborboa** [comment] 2021-03-12 02:48
Appears to be a dupe of #637, #652.

**Closed by zachborboa** 2021-03-12 02:48 UTC
