### ISSUE TITLE
Request data as plan text or xml

### ISSUE THREAD

**Issue by witul** [php-curl-class/php-curl-class#195] opened 2015-05-18 22:08 UTC
Hi. I found some problem with requesting post data which are not an array. Data are appended to request header without a key (headers value are exploded by colon). I wrote a simple solution for me, but of course it's just temporarily:

In function parseHeaders i added simple "if" to check post data beginning from "<?xml", then just skip loop by continue. It's ok for me right now, but it needs better approach.

**Comment by zachborboa** [comment] 2015-05-19 00:17
Hi. I've tested what you've described and I'm not able to reproduce. Is this a comparable test?

```php
$curl = new Curl();
$curl->post('http://httpbin.org/post', '<?xml version="1.0" encoding="UTF-8"?><rss>...</rss>');
var_dump($curl);
```

**Comment by zachborboa** [comment] 2015-07-31 07:37
Closing due to no reply. Thanks

**Closed by zachborboa** 2015-07-31 07:37 UTC
Labels: Needs More Info

**Comment by zachborboa** [comment] 2015-08-20 05:16
I believe this was the fix @witul used.

https://github.com/witul/php-curl-class/commit/ce4d1faa9b33e0a4775e8664c84ac18d8600cb0f

```php
     private function parseHeaders($raw_headers)
     {
         $raw_headers = preg_split('/\r\n/', $raw_headers, null, PREG_SPLIT_NO_EMPTY);
         $http_headers = new CaseInsensitiveArray();

         $raw_headers_count = count($raw_headers);
         for ($i = 1; $i < $raw_headers_count; $i++) {
+            if(substr($raw_headers[$i],0,5)=='<?xml')
+                continue;
             list($key, $value) = explode(':', $raw_headers[$i], 2);
             $key = trim($key);
             $value = trim($value);
             // Use isset() as array_key_exists() and ArrayAccess are not compatible.
             if (isset($http_headers[$key])) {
                 $http_headers[$key] .= ',' . $value;
             } else {
                 $http_headers[$key] = $value;
             }
         }

         return array(isset($raw_headers['0']) ? $raw_headers['0'] : '', $http_headers);
     }
```
