### ISSUE TITLE
Having issues trying to proxy my PDF's stored on Firebase Storage

### ISSUE THREAD

**Issue by inglesuniversal** [php-curl-class/php-curl-class#668] opened 2021-05-09 20:26 UTC
Is there a way to proxy this type of LINK?

Sample.pdf file provided as DEMO

[SAMPLE_PDF](https://firebasestorage.googleapis.com/v0/b/mycloudvip-storage.appspot.com/o/GMbRXZARq1AqDGD0xTZ4%2Fjz3rlts0VqgSwpatJj7I.pdf?alt=media&token=0e1e3629-9306-4e2c-aef0-1eab99d38728)

Why do I need to proxy these files?

Two main reasons, google does not allow custom domain so far (which I have requested a couple of weeks ago)

and I have a FLIPBOOK PDF reader which shows me the typical CORS error when trying to fetch the file from this domain:

https://firebasestorage.googleapis.com/

Hope you can help me.  Good luck!

**Comment by peter279k** [comment] 2021-05-10 01:27
I think you can refer the [setProxy Method](https://github.com/php-curl-class/php-curl-class/blob/master/src/Curl/Curl.php#L1158).

It seems to be helpful for resolving your issue.

**Comment by inglesuniversal** [comment] 2021-05-10 23:01
Yes I tried your suggestion and it went through.... Got an array with this:

object(stdClass)#9 (4) { ["args"]=> object(stdClass)#8 (0) { } ["headers"]=> object(stdClass)#10 (4) { ["Accept"]=> string(3) "*/*" ["Host"]=> string(11) "HOST.org" ["User-Agent"]=> string(95) "PHP-Curl-Class/9.1.0 (+https://github.com/php-curl-class/php-curl-class) PHP/7.4.15 curl/7.64.0" ["X-Amzn-Trace-Id"]=> string(40) "Root=XXXXXXXX" } ["origin"]=> string(14) "IP_ADDR" ["url"]=> string(23) "https://PROXY_DOMAIN/get" }

Now... how can I proxy files with this code using $_REQUEST[url] so that the file is shown as output instead of the array above. My knowledge of handling this type of out is still limited. Sorry for taking your time.


Best reagards

**Comment by inglesuniversal** [comment] 2021-05-11 00:08
Tried this but did not work :(

`require_once __DIR__ . '/vendor/autoload.php';

$url = $_REQUEST['url'];

$url = base64_decode($url);

if($url == null) { echo "Invalid URL"; exit; }

use Curl\Curl;

header('Accept-Ranges: none');
header('Content-Type: application/pdf');

$curl = new Curl();
$curl->setProxy('176.63.205.248', '54621');
$curl->setProxyTunnel();
$curl->get($url);
echo $curl->response;`

**Comment by peter279k** [comment] 2021-05-11 02:39
Thanks for your reply. I don't the proxy server and reproduce this issue at this moment.

I will try to find some APIs or proxy servers to reproduce the issue.

**Comment by inglesuniversal** [comment] 2021-05-11 02:50
I had the issue and found this... 

[GITHUB_PROXY_LIST](https://github.com/clarketm/proxy-list)

**Closed** 2021-05-24 03:03 UTC
